# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Inflatables.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Inflatables.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false Inflatables.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no